services:
  simulator:
    image: southamerica-east1-docker.pkg.dev/SEU_PROJETO/test-simulator/web:${APP_VERSION}
    container_name: test_simulator
    restart: always
    ports:
      - "127.0.0.1:8081:80"