name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - name: Test environment
        run: |
          echo "Runner funcionando"
          whoami
          hostname